### ISSUE TITLE
Make repo to be Predictoor-only

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-docs#1]
### TODOs
- [ ] Make landing page Predictoor-only (README.md)
- [ ] Update left-sidebar toc to be Predictoor-only (SUMMARY.md)
- [ ] Delete all non-Predictoor content
