### ISSUE TITLE
[EPIC] Port predictoor docs to oceanprotocol/pdr-docs

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-docs#9]
### TODOs

- [x] pdr-docs github repo, in with non pdr content removed, and pdr content promoted to top level
- [x] Predictoor docs gitbook, in Ocean Protocol org
- [x] github & gitbook linked appropriately / proper permissions
- [x] verified that I can do PRs with proper previews
- [x] add pdr-docs to [Predictoor zenhub](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/board)
- [x] publish to web, via gitbook -> share. Url: https://oceanprotocol.gitbook.io/predictoor-docs
- [x] stand it up on docs.predictoor.ai. gitbook directions: [high-level](https://docs.gitbook.com/published-documentation/custom-domain), [custom domain](https://docs.gitbook.com/published-documentation/custom-domain/initiate/space-level-custom-domain)
  - [x] via gandi, update DNS record for predictoor.ai
  - [x] (pending) let DNS record propagate - 3h+. [See whois value](https://who.is/dns/docs.predictoor.ai). [See propagation with whatsmydns](https://www.whatsmydns.net/#A/docs.predictoor.ai)
  - [x] via gitbook.com, "publish"
- [x] update oceanprotocol/docs repo, given new location. See [docs#1426](https://github.com/oceanprotocol/docs/issues/1426)
- [x] update predictoor.ai main: "about" points to docs.predictoor.ai. See [pdr-web#302](https://github.com/oceanprotocol/pdr-web/issues/302)
